# Generated by Django 4.2.1 on 2023-06-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0006_rename_content_post_text_remove_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
